function dataOut = argGenTest13(preTestDelay,  ...
                                sampleRate,    ...
                                postTestDelay, ...
                                profile,       ...
                                buffer,        ...
                                pDest,         ...
                                length,         ...
                                writeWait)
    dataOut = typecast(uint32(preTestDelay),           'uint8');
    dataOut = [dataOut typecast(uint32(sampleRate),    'uint8')];
    dataOut = [dataOut typecast(uint32(postTestDelay), 'uint8')];
    dataOut = [dataOut typecast(uint8(profile),        'uint8')];
    dataOut = [dataOut typecast(uint8(buffer),         'uint8')];
    dataOut = [dataOut typecast(uint32(pDest),         'uint8')];
    dataOut = [dataOut typecast(uint16(length),        'uint8')];
    dataOut = [dataOut typecast(uint16(writeWait),     'uint8')];
end
