function dataOut = argGenTest14(preTestDelay,  ...
                                sampleRate,    ...
                                postTestDelay, ...
                                profile,       ...
                                measure,        ...
                                read,         ...
                                convert)
    dataOut = typecast(uint32(preTestDelay),           'uint8');
    dataOut = [dataOut typecast(uint32(sampleRate),    'uint8')];
    dataOut = [dataOut typecast(uint32(postTestDelay), 'uint8')];
    dataOut = [dataOut typecast(uint8(profile),        'uint8')];
    dataOut = [dataOut typecast(uint8(measure),        'uint8')];
    dataOut = [dataOut typecast(uint8(read),           'uint8')];
    dataOut = [dataOut typecast(uint8(convert),        'uint8')];
end
